name: monedario
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  font_awesome_flutter: ^10.7.0

  # Dependencias de Firebase 
  firebase_auth: ^5.6.2         # Para login/registro
  cloud_firestore: ^5.6.11      # Para base de datos 
  firebase_storage: ^12.4.9     # Para subir archivos
  google_sign_in: ^6.2.1        # Para autenticación con Google

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   
    - assets/google.png
    - assets/facebook.png
    - assets/apple.png
    - assets/cata_register.png
    - assets/polita_login.png