// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4jd4kF0wcyHkz0HYnjSPkWG3kJRz1Fzk',
    appId: '1:872567223101:web:43a2229777b563e3968b54',
    messagingSenderId: '872567223101',
    projectId: 'monedarioapp',
    authDomain: 'monedarioapp.firebaseapp.com',
    storageBucket: 'monedarioapp.firebasestorage.app',
    measurementId: 'G-3S02P2N9C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6tustW851rjFZ84YfTDH7gVllbfVLjD8',
    appId: '1:872567223101:android:ee6b5fc6c2b96883968b54',
    messagingSenderId: '872567223101',
    projectId: 'monedarioapp',
    storageBucket: 'monedarioapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI3Thz_Y_vViqpW2XrpOH-dKjN2t745l0',
    appId: '1:872567223101:ios:a1e4d4e0476db6f8968b54',
    messagingSenderId: '872567223101',
    projectId: 'monedarioapp',
    storageBucket: 'monedarioapp.firebasestorage.app',
    androidClientId: '872567223101-6evfhafs25s9gv166gako8g6rv68f86e.apps.googleusercontent.com',
    iosClientId: '872567223101-alemgjqasrmu7r235fq9cophomv0026n.apps.googleusercontent.com',
    iosBundleId: 'com.example.monedario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI3Thz_Y_vViqpW2XrpOH-dKjN2t745l0',
    appId: '1:872567223101:ios:a1e4d4e0476db6f8968b54',
    messagingSenderId: '872567223101',
    projectId: 'monedarioapp',
    storageBucket: 'monedarioapp.firebasestorage.app',
    androidClientId: '872567223101-6evfhafs25s9gv166gako8g6rv68f86e.apps.googleusercontent.com',
    iosClientId: '872567223101-alemgjqasrmu7r235fq9cophomv0026n.apps.googleusercontent.com',
    iosBundleId: 'com.example.monedario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4jd4kF0wcyHkz0HYnjSPkWG3kJRz1Fzk',
    appId: '1:872567223101:web:a98bb606f9dc227d968b54',
    messagingSenderId: '872567223101',
    projectId: 'monedarioapp',
    authDomain: 'monedarioapp.firebaseapp.com',
    storageBucket: 'monedarioapp.firebasestorage.app',
    measurementId: 'G-L85JTD7CCS',
  );
}
